services:
  redis:
    image: redis:alpine3.22
    container_name: elect-shop-redis
    ports:
      - "6379:6379"
  mysql-db:
    image: mysql:8.4.6
    container_name: elect-shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elect_shop
    ports:
      - "3306:3306"